# -*- coding: utf-8 -*-
"""Thompson Sampling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLw8Fm-fy0jo7xg9KU7pf73LwJe1zvAC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Ads_CTR_Optimisation.csv')

import random
N = 10000
d = 10
ads_selected = []
number_of_rewards_1 = [0] * d
number_of_rewards_0 = [0] * d
total_rewards = 0
for n in range(0,N):
  ad = 0
  max_beta_reward = 0
  for i in range(0,d):
    beta_reward = random.betavariate(number_of_rewards_1[i] + 1, number_of_rewards_0[i] + 1)
    if (beta_reward > max_beta_reward):
      max_beta_reward = beta_reward
      ad = i
  ads_selected.append(ad)
  reward = df.values[n,ad]
  if reward == 1:
    number_of_rewards_1[ad] = number_of_rewards_1[ad] +1
  else:
    number_of_rewards_0[ad] = number_of_rewards_0[ad] +1
  total_rewards = total_rewards +reward

plt.hist(ads_selected)
plt.title('Histogram of ads selections')
plt.xlabel('Ads')
plt.ylabel('Number of times each ad was selected')
plt.show()